services:
  redis:
    image: redis:latest
    container_name: light_off_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  light_off:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: light_off_service
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: python main.py
